### ISSUE TITLE
Collapse dead times

### ISSUE THREAD

**Issue by cmanibog** [ft-interactive/visual-vocabulary#140]
Simple-line template: collapse weekends and hours when markets are closed.

**Comment by bobhaslett** [comment]
This is now done, There is an intraday variable in the user defined variable section that can be set to true. This will omit any date that is not in the dataset from the timeline. Please note that this is not the same as a date with no value.  If you have a value in the date column for Sat-Dec-02 and an empty cell next to it this will still be included. To omit it you would need to remove the whole row from the dataset so that the date column would read 01/12/2017, 03/12/2017, 04/12/2017...
